// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pqkhtgdmgnneooleniis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxa2h0Z2RtZ25uZW9vbGVuaWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTA5MDEsImV4cCI6MjA2MDA2NjkwMX0.Mo_zOzYdIWbfJIDGB2B6Do7IYpuqqLit11_3lf7KiC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);